apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "myDatabase"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db  # Default MongoDB data directory
      initContainers:
      - name: s3-sync
        image: amazonlinux:2
        command: ["sh", "-c", "yum install -y s3fs-fuse && mkdir -p /data/db && s3fs my-s3-bucket /data/db -o iam_role=auto && cp -r /data/db/* /mnt/mongo && umount /data/db"]
        volumeMounts:
        - name: mongodb-storage
          mountPath: /mnt/mongo
      volumes:
      - name: mongodb-storage
        emptyDir: {}
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-credentials
data:
  AWS_ACCESS_KEY_ID: <your-access-key-id>
  AWS_SECRET_ACCESS_KEY: <your-secret-access-key>
--- 
#https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
#https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html

kubectl apply -f s3-credentials-configmap.yaml
kubectl apply -f mongodb-deployment.yaml
kubectl get pods
kubectl describe pod <POD_NAME>
kubectl logs <POD_NAME> -c s3-sync
