apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  iopsPerGiB: "50" # Optional, default settings
  throughput: "125" # Optional, default throughput
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
