#Steps to Create and Manage Roles and RoleBindings
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Specify the namespace
  name: pod-reader
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["pods"]  # Specify the resources
  verbs: ["get", "list", "watch"]  # Allowed actions
--- 
# Role Binding 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default # Same namespace as the Role
subjects:
- kind: User  # Could be User, Group, or ServiceAccount
  name: john-doe  # Replace with the actual username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # Name of the Role being assigned
  apiGroup: rbac.authorization.k8s.io
### 
# kubectl get roles -n example-namespace
# kubectl get rolebindings -n example-namespace

